language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=3.2.*
  
before_script:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/validator:${SYMFONY_VERSION}" --no-update; fi;
  - if [ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]; then composer require --dev "phpunit/phpunit:^5.6" --no-update; fi;
  - composer install --dev --no-interaction

script:
   - ./bin/phpunit --testsuite=Unit
